import { ILanguageParam } from '@/app-constants';

export const pronunciationWords = {
  [ILanguageParam.russian]: [
    'вопрос',
    'время',
    'год',
    'голова',
    'дело',
    'день',
    'дом',
    'друг',
    'жизнь',
    'конец',
    'лицо',
    'место',
    'мир',
    'работа',
    'раз',
    'ребенок',
    'рука',
    'сила',
    'слово',
    'случай',
    'сторона',
    'страна',
    'человек',
    'красный',
    'ораньжевый',
    'желтый',
    'зеленый',
    'синий',
    'фиолетовый',
    'чёрный',
    'белый',
    'круг',
    'квадрат',
    'треугольник',
  ],
  [ILanguageParam.english]: [] as string[],
  [ILanguageParam.french]: [] as string[],
  [ILanguageParam.spanish]: [] as string[],
};
