import { ILanguageParam } from '@/app-constants';

export const pronunciationWords = {
  [ILanguageParam.russian]: [
    'ВОПРОС',
    'ВРЕМЯ',
    'ГОД',
    'ГОЛОВА',
    'ДЕЛО',
    'ДЕНЬ',
    'ДОМ',
    'ДРУГ',
    'ЖИЗНЬ',
    'КОНЕЦ',
    'ЛИЦО',
    'МЕСТО',
    'МИР',
    'РАБОТА',
    'РАЗ',
    'РЕБЕНОК',
    'РУКА',
    'СИЛА',
    'СЛОВО',
    'СЛУЧАЙ',
    'СТОРОНА',
    'СТРАНА',
    'ЧЕЛОВЕК',
    'КРАСНЫЙ',
    'ОРАНЬЖЕВЫЙ',
    'ЖЕЛТЫЙ',
    'ЗЕЛЕНЫЙ',
    'СИНИЙ',
    'ФИОЛЕТОВЫЙ',
    'ЧЁРНЫЙ',
    'БЕЛЫЙ',
    'КРУГ',
    'КВАДРАТ',
    'ТРЕУГОЛЬНИК',
  ],
  [ILanguageParam.english]: [] as string[],
  [ILanguageParam.french]: [] as string[],
  [ILanguageParam.spanish]: [] as string[],
};
